#!/bin/bash
# Script para remover imagens originais nao otimizadas do repositorio lsf
# Rode este script DENTRO da pasta local do repositorio (C:\lsf), via Git Bash
set -e

git rm "bg_lsf_planta.png"
git rm "espacosmart_logo.png"
git rm "finabase_logo.png"
git rm "hero_blueprint.png"
git rm "image_hero.png"
git rm "imperatriz_logo.png"
git rm "leal_logo.png"
git rm "projeto_1.png"
git rm "projeto_2.png"
git rm "projeto_3.png"
git rm "projeto_4.jpg"
git rm "projeto_5.jpg"
git rm "projeto_ar.jpg"
git rm "projetos/lsf01/02_Casa da Mata - Vista frontal central.jpg"
git rm "projetos/lsf01/04_Casa da Mata - Vista posterior central.jpg"
git rm "projetos/lsf01/05_Casa da Mata - Vista lateral esquerda.jpg"
git rm "projetos/lsf01/07_Casa da Mata - Integração interna.jpg"
git rm "projetos/lsf01/08_Casa da Mata - Piscina.jpg"
git rm "projetos/lsf01/09_Casa da Mata - Detalhe integração.jpg"
git rm "projetos/lsf02/01_Casa AR - vista frontal 01.jpg"
git rm "projetos/lsf02/02_Casa AR - vista frontal 02.jpg"
git rm "projetos/lsf02/03_Casa AR - vista frontal interna 01.jpg"
git rm "projetos/lsf02/04_Casa AR - vista frontal interna 02.jpg"
git rm "projetos/lsf02/07_Casa AR - vista posterior 03.jpg"
git rm "projetos/lsf03/01_Casa Carvalho - vista frontal esquerda.jpg"
git rm "projetos/lsf03/03Casa Carvalho - Hall de acesso.jpg"
git rm "projetos/lsf03/04_Casa Carvalho - vista lateral direita.jpg"
git rm "projetos/lsf03/05_Casa Carvalho - acesso veículos.jpg"
git rm "projetos/lsf03/06_Casa Carvalho - vista lateral direita 2.jpg"
git rm "projetos/lsf03/09_Casa Carvalho - detalhe área de lazer.jpg"
git rm "projetos/lsf03/10_Casa Carvalho - detalhe piscina.jpg"
git rm "projetos/lsf04/01_Casa Robertson - Vista frontal esquerda.jpg"
git rm "projetos/lsf04/02_Casa Robertson - Vista frontal central.jpg"
git rm "projetos/lsf04/03_Casa Robertson - Vista frontal direita.jpg"
git rm "projetos/lsf04/04_Casa Robertson - Vista posterior direita.jpg"
git rm "projetos/lsf04/05_Casa Robertson - Vista posterior central.jpg"
git rm "projetos/lsf04/CAPA_Casa Robertson - Vista frontal central - Copy.jpg"
git rm "projetos/lsf05/01.png"
git rm "projetos/lsf05/02.png"
git rm "strip_01de01.png"
git rm "strip_1of3.png"
git rm "strip_2of3.png"
git rm "strip_3of3.png"

git commit -m "remove imagens originais nao otimizadas (nao usadas pelo site)"
git push
